const SKULL_SHEET_URL = new URL("../../assets/enemies/skull_sheet.png", import.meta.url).href;

export const ENEMY_DEFINITIONS = {
  // Stubs — replace spriteSheetUrl when sprite sheets are available
  grunt: {
    animation: { delayMs: 120, from: 0, to: 3 },
    attackCooldownSeconds: 1.5,
    attackDamage: 10,
    attackRange: 200,
    bobAmplitude: 0,
    bobSpeed: 0,
    cellHeight: 256,
    cellWidth: 256,
    health: 40,
    hitRadius: 20,
    name: "grunt",
    movementMode: "ground",
    sightRange: 400,
    size: 56,
    speed: 36,
    spriteSheetUrl: SKULL_SHEET_URL, // placeholder
    modelUrl: "/models/enemies/soldier.glb",
  },

  zombie: {
    animation: { delayMs: 150, from: 0, to: 3 },
    attackCooldownSeconds: 2.0,
    attackDamage: 15,
    attackRange: 64,
    bobAmplitude: 0,
    bobSpeed: 0,
    cellHeight: 256,
    cellWidth: 256,
    health: 60,
    hitRadius: 20,
    name: "zombie",
    movementMode: "ground",
    sightRange: 300,
    size: 56,
    speed: 24,
    spriteSheetUrl: SKULL_SHEET_URL, // placeholder
    modelUrl: "/models/enemies/zombie.glb",
  },

  knight: {
    animation: { delayMs: 100, from: 0, to: 3 },
    attackCooldownSeconds: 1.2,
    attackDamage: 20,
    attackRange: 80,
    bobAmplitude: 0,
    bobSpeed: 0,
    cellHeight: 256,
    cellWidth: 256,
    health: 75,
    hitRadius: 22,
    name: "knight",
    movementMode: "ground",
    sightRange: 420,
    size: 64,
    speed: 40,
    spriteSheetUrl: SKULL_SHEET_URL, // placeholder
    modelUrl: "/models/enemies/knight.glb",
    modelFootLift: 10,
  },

  ogre: {
    animation: { delayMs: 110, from: 0, to: 3 },
    attackCooldownSeconds: 1.8,
    attackDamage: 25,
    attackRange: 320,
    bobAmplitude: 0,
    bobSpeed: 0,
    cellHeight: 256,
    cellWidth: 256,
    health: 100,
    hitRadius: 28,
    name: "ogre",
    movementMode: "ground",
    sightRange: 450,
    size: 72,
    speed: 30,
    spriteSheetUrl: SKULL_SHEET_URL, // placeholder
    modelUrl: "/models/enemies/ogre.glb",
  },

  fiend: {
    animation: { delayMs: 90, from: 0, to: 3 },
    attackCooldownSeconds: 0.8,
    attackDamage: 30,
    attackRange: 96,
    bobAmplitude: 0,
    bobSpeed: 0,
    cellHeight: 256,
    cellWidth: 256,
    health: 120,
    hitRadius: 30,
    name: "fiend",
    movementMode: "ground",
    sightRange: 500,
    size: 72,
    speed: 58,
    spriteSheetUrl: SKULL_SHEET_URL, // placeholder
    modelUrl: "/models/enemies/fiend.glb",
  },

  shambler: {
    animation: { delayMs: 130, from: 0, to: 3 },
    attackCooldownSeconds: 2.5,
    attackDamage: 50,
    attackRange: 96,
    bobAmplitude: 0,
    bobSpeed: 0,
    cellHeight: 256,
    cellWidth: 256,
    health: 250,
    hitRadius: 40,
    name: "shambler",
    movementMode: "ground",
    sightRange: 600,
    size: 96,
    speed: 28,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/shambler.glb",
  },

  // Quake standard monster names — stats match original Quake QuakeC
  soldier: {
    animation: { delayMs: 120, from: 0, to: 3 },
    attackCooldownSeconds: 1.5,
    attackDamage: 10,
    attackRange: 200,
    bobAmplitude: 0, bobSpeed: 0,
    cellHeight: 256, cellWidth: 256,
    health: 30, hitRadius: 20,
    name: "soldier",
    movementMode: "ground",
    sightRange: 400,
    size: 56,
    speed: 36,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/soldier.glb",
  },

  dog: {
    animation: { delayMs: 80, from: 0, to: 3 },
    attackCooldownSeconds: 0.7,
    attackDamage: 8,
    attackRange: 64,
    bobAmplitude: 0, bobSpeed: 0,
    cellHeight: 256, cellWidth: 256,
    health: 25, hitRadius: 18,
    name: "dog",
    movementMode: "ground",
    sightRange: 350,
    size: 40,
    speed: 64,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/dog.glb",
  },

  hell_knight: {
    animation: { delayMs: 100, from: 0, to: 3 },
    attackCooldownSeconds: 1.0,
    attackDamage: 25,
    attackRange: 96,
    bobAmplitude: 0, bobSpeed: 0,
    cellHeight: 256, cellWidth: 256,
    health: 90, hitRadius: 28,
    name: "hell_knight",
    movementMode: "ground",
    sightRange: 500,
    size: 72,
    speed: 50,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/hell_knight.glb",
  },

  wizard: {
    animation: { delayMs: 90, from: 0, to: 3 },
    attackCooldownSeconds: 1.2,
    attackDamage: 15,
    attackRange: 300,
    bobAmplitude: 4, bobSpeed: 2.0,
    cellHeight: 256, cellWidth: 256,
    health: 80, hitRadius: 22,
    name: "wizard",
    movementMode: "hover",
    sightRange: 480,
    size: 56,
    speed: 48,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/wizard.glb",
  },

  shalrath: {
    animation: { delayMs: 110, from: 0, to: 3 },
    attackCooldownSeconds: 2.0,
    attackDamage: 20,
    attackRange: 350,
    bobAmplitude: 0, bobSpeed: 0,
    cellHeight: 256, cellWidth: 256,
    health: 200, hitRadius: 32,
    name: "shalrath",
    movementMode: "ground",
    sightRange: 520,
    size: 80,
    speed: 36,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/shalrath.glb",
  },

  tarbaby: {
    animation: { delayMs: 100, from: 0, to: 3 },
    attackCooldownSeconds: 0.5,
    attackDamage: 40,
    attackRange: 64,
    bobAmplitude: 2, bobSpeed: 3.0,
    cellHeight: 256, cellWidth: 256,
    health: 80, hitRadius: 20,
    name: "tarbaby",
    movementMode: "hover",
    sightRange: 300,
    size: 40,
    speed: 72,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/tarbaby.glb",
  },

  fish: {
    animation: { delayMs: 90, from: 0, to: 3 },
    attackCooldownSeconds: 0.8,
    attackDamage: 10,
    attackRange: 64,
    bobAmplitude: 3, bobSpeed: 2.5,
    cellHeight: 256, cellWidth: 256,
    health: 25, hitRadius: 18,
    name: "fish",
    movementMode: "hover",
    sightRange: 280,
    size: 40,
    speed: 56,
    spriteSheetUrl: SKULL_SHEET_URL,
    modelUrl: "/models/enemies/fish.glb",
  },
};

export function getEnemyDefinition(type) {
  return ENEMY_DEFINITIONS[type] ?? null;
}
